### ISSUE TITLE
__sub__ does not work for CompoundGeometry

### ISSUE THREAD

**Issue by robbievanleeuwen** [robbievanleeuwen/section-properties#194]
The subtract operator `__sub__` does not appear to work as intended for `CompoundGeometry` objects.

I've been trying to modify the reinforced concrete library methods to generate geometry without any overlapping areas, see following example. Given the following methods:

```python
def concrete_rectangular_section(
    b: float,
    d: float,
    dia: float,
    n_bar: int,
    n_circle: int,
    cover: float,
    area: float = None,
    conc_mat: pre.Material = pre.DEFAULT_MATERIAL,
    steel_mat: pre.Material = pre.DEFAULT_MATERIAL,
) -> geometry.CompoundGeometry:
  
    if n_bar < 2:
        raise ValueError("Please provide 2 or more steel reinforcing bars.")

    geom = primitive_sections.rectangular_section(b=b, d=d, material=conc_mat)

    x_i = cover + dia / 2
    spacing = (b - 2 * cover - dia) / (n_bar - 1)

    for i in range(n_bar):
        if area:
            bar = primitive_sections.circular_section_by_area(
                area=area, n=n_circle, material=steel_mat
            )
        else:
            bar = primitive_sections.circular_section(
                d=dia, n=n_circle, material=steel_mat
            )

        bar = bar.shift_section(x_offset=x_i + spacing * i, y_offset=cover + dia / 2)

        geom = add_reinforcement(base_geom=geom, reinforcement=bar)

    return geom
```

```python
def add_reinforcement(
    base_geom: Union[geometry.Geometry, geometry.CompoundGeometry],
    reinforcement: geometry.Geometry,
):
    """Adds reinforcement geometry to a base concrete geometry object."""

    # make hole for reinforcement
    base_geom = base_geom - reinforcement

    # add reinforcement
    base_geom = base_geom + reinforcement

    # remove hole created in first operation
    base_geom.holes.pop()

    return base_geom
```

Running the following:

```python
from sectionproperties.pre.library.concrete_sections import concrete_rectangular_section
from sectionproperties.pre.pre import Material
from sectionproperties.analysis.section import Section

concrete = Material(
    name='Concrete', elastic_modulus=30.1e3, poissons_ratio=0.2, yield_strength=32,
    density=2.4e-6, color='lightgrey'
)
steel = Material(
    name='Steel', elastic_modulus=200e3, poissons_ratio=0.3, yield_strength=500,
    density=7.85e-6, color='grey'
)

geometry = concrete_rectangular_section(
    b=300, d=600, dia=20, n_bar=3, n_circle=24, cover=30, conc_mat=concrete, steel_mat=steel
)
geometry.create_mesh(mesh_sizes=[500])
geometry.plot_geometry()

sec = Section(geometry)
sec.plot_mesh()
```

Results in the following:

```shell
Traceback (most recent call last):
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/geometry.py", line 1051, in __sub__
    if self.assigned_control_point and new_polygon.contains(
AttributeError: 'CompoundGeometry' object has no attribute 'assigned_control_point'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 14, in <module>
    geometry = concrete_rectangular_section(
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/library/concrete_sections.py", line 93, in concrete_rectangular_section
    geom = add_reinforcement(base_geom=geom, reinforcement=bar)
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/library/concrete_sections.py", line 288, in add_reinforcement
    base_geom = base_geom - reinforcement
  File "/Users/robbievanleeuwen/Documents/Programming/section-properties/sectionproperties/pre/geometry.py", line 1057, in __sub__
    raise ValueError(
ValueError: Cannot perform 'difference' on these two objects: <sectionproperties.pre.geometry.CompoundGeometry object at 0x7fa4e52cae50> - <sectionproperties.pre.geometry.Geometry object at 0x7fa4e52caca0>
```

Adding `self.assigned_control_point = None` to the `__init__` of `CompoundGeometry` fixes this, but results in the previous reinforcing bars being deleted and only the rectangular concrete section remaining when `base_geom = base_geom - reinforcement` is run. As a result seems like this method only really works on `Geometry` objects and not `CompoundGeometry` objects. Here is the end result:

<img width="421" alt="Screen Shot 2022-02-23 at 4 29 07 pm" src="https://user-images.githubusercontent.com/18841910/155266256-d60fb107-04f5-4ba9-b5ad-e4f142c199f2.png">

Would it be possible to get the subtract operator to work for `CompoundGeometry`? Or am I doing something wrong here :)

**Comment by connorferster** [comment]
I have been meaning to take a look at this. Will follow-up this week. Thanks for investigating it!

**Comment by connorferster** [comment]
@robbievanleeuwen #198 does not address this. 

Question, when I run this code on it's own, it seems to work:

```python
from sectionproperties.pre.library.concrete_sections import concrete_rectangular_section
from sectionproperties.pre.pre import Material
from sectionproperties.analysis.section import Section

concrete = Material(
    name='Concrete', elastic_modulus=30.1e3, poissons_ratio=0.2, yield_strength=32,
    density=2.4e-6, color='lightgrey'
)
steel = Material(
    name='Steel', elastic_modulus=200e3, poissons_ratio=0.3, yield_strength=500,
    density=7.85e-6, color='grey'
)

geometry = concrete_rectangular_section(
    b=300, d=600, dia=20, n_bar=3, n_circle=24, cover=30, conc_mat=concrete, steel_mat=steel
)
geometry.create_mesh(mesh_sizes=[500])
geometry.plot_geometry()

sec = Section(geometry)
sec.plot_mesh()
```

However, when I override the `concrete_rectangular_section` function with the one you have provided above, I get the same error. I see the "cause" of the error plainly enough but I think there is something else at play. Will submit a separate PR for this.

**Comment by robbievanleeuwen** [comment]
@connorferster sounds good, I just updated the code in #198 at the same time you were typing this. Happy for it to be a separate PR :)
